### ISSUE TITLE
An error occured when importing gmdl file

### ISSUE THREAD

**Issue by Space-Occupied** [emd4600/SporeModder-Blender-Addons#17]
An error occured when I import gmdl file:
`Python: Traceback (most recent call last):
  File "C:\Users\23138\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SporeModder-Blender-Addons-master\__init__.py", line 71, in execute
    return import_gmdl(file, False, self.filepath)
  File "C:\Users\23138\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SporeModder-Blender-Addons-master\gmdl_importer.py", line 304, in import_gmdl
    b_mesh.vertices[i].normal = rw4_enums.unpack_normals(v.normal)
AttributeError: bpy_struct: attribute "normal" from "MeshVertex" is read-only`
It only have the creature's shape but lost all colors...
I tried different versions of blender such as 2.8,3.2,3.3 but it still has the same problem.

**Comment by emd4600** [comment]
Fixed in commit 16739dc4b8c1e61fd4c683a9288211bca6581e22
