### ISSUE TITLE
Blender Addons do not work in Blender 4.0.1

### ISSUE THREAD

**Issue by MartynDerg** [emd4600/SporeModder-Blender-Addons#23]
Addon fails to install in Blender 4.0.1
`Read prefs: "C:\Users\Martyn\AppData\Roaming\Blender Foundation\Blender\4.0\config\userpref.blend"
Failed to register scene update handler
addon_utils.disable: sporemodder not disabled
Modules Installed (sporemodder) from 'C:\\Users\\Martyn\\Downloads\\SporeModder.Blender.3.Addons.zip' into 'C:\\Users\\Martyn\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons'
sporemodder_addons updater verbose is enabled
sporemodder_addons Updater: Read in JSON settings from file
Exception in module register(): C:\Users\Martyn\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sporemodder\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\Martyn\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sporemodder\__init__.py", line 193, in register
    from . import rw4_material_config, rw4_animation_config, anim_bone_config
  File "C:\Users\Martyn\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sporemodder\rw4_animation_config.py", line 217, in <module>
    shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '3D_UNIFORM_COLOR'`

**Comment by AbbyRead** [comment]
I'm likewise getting:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\AbbyR\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\sporemodder\__init__.py", line 193, in register
    from . import rw4_material_config, rw4_animation_config, anim_bone_config
  File "C:\Users\AbbyR\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\sporemodder\rw4_animation_config.py", line 217, in <module>
    shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '3D_UNIFORM_COLOR'

**Comment by AbbyRead** [comment]
Does work in LTS 3.6 though.
https://www.blender.org/download/lts/3-6/

**Comment by Kade-N** [comment]
Has since been updated https://github.com/Spore-Community/SporeModder-Blender-Addons/releases
