### ISSUE TITLE
Blender can't install and show this message 

### ISSUE THREAD

**Issue by darkkostas25** [emd4600/SporeModder-Blender-Addons#9]
Traceback (most recent call last):
  File "D:\Steam\steamapps\common\Blender\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\theda\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sporemodder\__init__.py", line 171, in register
    addon_updater_ops.register(bl_info)
  File "C:\Users\theda\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sporemodder\addon_updater_ops.py", line 1424, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'addon_updater_install_popup'

**Comment by MrSquidPants** [comment]
I get the same thing!
